# -*- coding: utf-8 -*-
"""est-dades.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rRS7VcP5TP0q3Z3LWeOnaUH8NulESDNz
"""

print('-' * 20)
print('Utilització de Llistes')
print('-' * 20)
'''
Concepte: Una llista és una estructura de dades que permet guardar
múltiples valors dins d’una sola variable.
Important:
* Ordenada
* Indexada
* Mutable (es pot modificar)
* Pot contenir diferents tipus de dades
'''

#Creació d'una llista
'''
Podem crear llistes amb valors d'un únic tipus o barrejar-los
'''
numbers = [10,20,30]
names = ['Dani','Pikachu', 'Alba']
mix = [1,'Tanjiro', True, 10.5]

#Accéss als elements (indexació)
'''
Cada element té una posició (índex)
El primer element és l'índex (0)
L'últim és -1
'''
print(names[0]) #Primer valor
print(names[-1]) #Últim valor
print(names) #Mostra tots els valors de la llista

#Modificar elements
names[0] = "Charmander"
print(names)
print(names[0])

#Afegir elements
names.append('Macarena') #Afegeix al final
names.insert(1,'Julio') #Afegeix a una posició concreta (en aquest cas posició 1)

#Eliminar elements
'''
Important: Si no troba l'element a esborrar el programa peta.
Hem de comprobar si existeis abans d'eliminar
Quan eliminem la resta d'elements es mouen cap a l'esquerra (com en una cua d'una tenda)
'''
print(f"Llista abans d'eliminar: {names}")
names.remove('Charmander') #Elimina per valor
print(f"Llista després d'eliminar: {names}")

'''
COMPROVAR ABANS D'ESBORRAR
'''
if "Charmander" in names:
  names.remove(f"S'ha eliminat Charmander")
else:
  print("Charmander no existeix a la llista")

print(f"Llista abans d'eliminar: {names}")
names.pop(0) #Elimina per posició
print(f"Llista després d'eliminar: {names}")

#Longitud de la llista
print(len(names))

#Recórrer una llista
print("Recórrer una llista")
'''
Forma bàsica
'''
print("Forma bàsica (per valor)")
for nom_usuari in names: #nom_usuari és el nom que he decidit per la variable (podem posar el que vulguem)
  print(nom_usuari)

'''
Forma amb índex
'''
print("Forma amb índex")
for i in range(len(names)):
  print(i, names[i])

print('-' * 20)
print('Utilització de tuples')
print('-' * 20)
'''
Concepte: Una tupla és una estructura de dades que permet guardar múltiples
valors dins d’una sola variable, igual que una llista.
Important:
* Ordenada
* Indexada
* NO Mutable (NO es pot modificar)
* Pot contenir diferents tipus de dades
'''

#Creació d'una tupla
numbers = (10,20,30)
names_users = ("Ana", "Felipe", "Marta")
mix_var = (1,"Ana", True, 3.1)

'''Cas especial: ERROR TÍPIC'''
t = (5,) #Tupla d'un sol element
t = (5) #NO és una tupla, és un int

#Accéss als elements (funciona igual que amb llistes)
print(names_users[0])
print(names_users[-1])

#Modificació (NO ES PODEN MODIFICAR)
'''numbers[0] = 4 <- DONA ERROR (TypeError: 'tuple' object does not support item assignment)'''

#Recórrer una tupla
print("Recórrer una tupla")
'''
Forma per valor
'''
print("Forma per valor")
for name in names_users:
  print(name)

'''
Forma amb índex
'''
print("Forma amb índex")
for i in range(len(names_users)):
  print(i, names_users[i])

print('-' * 20)
print('Utilització de diccionaris')
print('-' * 20)
'''
Concepte: Un diccionari és una estructura de dades que guarda informació en format: clau - valor
Important:
* Mutable
* NO Indexada (No té posicions numèriques)
* Accés per clau
* Pot contenir diferents tipus de dades
'''

#Creació d'un diccionari
'''
Cada element te una clau i un valor
El primer element fa referència a la clau
El segon element fa refèrencia al valor d'aquesta clau
clau : valor
Exemple:
clau : nom - valor: Gabimaru
'''
alumne = {
    "nom" : "Gabimaru",
    "edat" : 18,
    "estil" : "ninja",
    "isMale" : True
}

#Accés als valors (Si la clau no existeix dona error)
print(alumne["nom"])
print(alumne['edat'])
'''print(alumne['attack']) -> ERROR NO EXISTEIX LA CLAU ATTACK'''

#Afegir o modificar valors
alumne["edat"] = 20
alumne["nickname"] = 'El vacío'

print(alumne['nickname'])

#Eliminar elements (Si la clau no existeix dona error)
del alumne["isMale"] #Opció 1
alumne.pop("edat") #Opció 2

'''
COMPROVAR ABANS D'ESBORRAR
'''
#Opció 1
if "edat" in alumne:
  print(alumne["edat"])
else:
  print("L'alumne no té l'atribut edat")

#Opció 2 (Si no el troba retorna NONE, però no peta)
print(f"Edat de l'alumne: {alumne.get('edat')}")

#Opció 2 versió millorada (Si no el troba retorna podem retornar un valor per defecta i no peta)
print(f"Edat de l'alumne: {alumne.get('edat',"No definit")}")
print(f"Edat de l'alumne: {alumne.get('edat',0)}")

#Recórrer un diccionari
''' Recórrer per clau'''
for clau in alumne:
  print(clau)

'''Recórrer per valor'''
for valor in alumne.values():
  print(valor)

'''Recórrer per clau-valor'''
for clau, valor in alumne.items():
  print(f"{clau} : {valor}")

print('-' * 20)
print('Utilització de conjunts')
print('-' * 20)
'''
Concepte: Un conjunt (set) és una estructura de dades que guarda múltiples valors,
però amb dues característiques importants:
* NO permet duplicats
* No està ordenat

Important:
* Mutable
* NO Indexada (No té posicions numèriques)
* Ideal per operacions matemàtiques
'''

#Creació d'un conjunt amb dades
enemics = {"orc", "drac", "zombi"} #Amb valors

#Creació d'un conjunt buit
players = set()
users = ()

'''NO PERMET DUPLICATS (Encara que li posem, no fa cas)'''
numbers = {1,2,3,3,3,4}
print(numbers)

enemics.add("orc")
enemics.add("ORC") #No és el mateix ORC que orc (Case sensitive)
print(enemics)

#Afegir elements
enemics.add("esquelet")

#Eliminar elements
enemics.remove("ORC")

''' SI NO EXISTEIX DONA ERROR
enemics.remove("pepe") -> DONA ERROR
'''
#Eliminar elements de manera segura
print(f"Llista sense eliminar:{enemics}")
enemics.discard("pepe") #NO PETA
enemics.discard("drac")
print(f"Llista eliminant drac:{enemics}")

'''
NO PODEM ACCEDIR PER ÍNDEX (ELS CONJUNTS NO TENEN NI ORDRE NI POSICIÓ)
enemics[0] -> ERROR
'''

#Recórrer un conjunt (L'ordre pot variar a cada execució)
for enemic in enemics:
  print(enemic)

#Operacions matemàtiques
habilitats_jugador = {"espasa", "magia", "furtivitat"}
habilitats_enemic = {"magia", "volar"}

#Unió (Elements de tots dos)
print("Unió (Elements de tots dos)")
print(habilitats_jugador | habilitats_enemic)

#Intersecció (Elements comuns)
print("Intersecció (Elements comuns)")
print(habilitats_jugador & habilitats_enemic)

#Diferència (Elements que estan al set 1 i NO al set 2)
print("Diferència (Elements que estan al set 1 i NO al set 2)")
print(habilitats_jugador - habilitats_enemic)

#Diferència simètrica (Elements que no són comuns)
print("Diferència simètrica (Elements que no són comuns)")
print(habilitats_jugador ^ habilitats_enemic)